/// Emits a Dockerfile (+ `.dockerignore`) that bakes a resolved **arm-gnu**
/// cross toolchain + sysroot into an OCI image, so CI pulls a ready toolchain
/// instead of re-downloading and extracting it every run.
///
/// The build context is the provider's platform dir
/// (`cross-<triple>-<sysrootKey>/`), so the only `COPY` sources are its
/// `toolchain/` and `sysroot/` subdirs. The image bakes them at a **fixed**
/// workspace (`/emb`) under the same `cross-<triple>-<sysrootKey>` path emb
/// computes, so a later `emb cross <manifest> --build -w /emb` resolves as a
/// cache hit (the providers skip download/extract when the dir is populated)
/// and only re-emits the toolchain file for the in-image paths.
///
/// The sysroot's symlinks are relativized at resolve time, so it relocates from
/// the build host's path to `/emb` cleanly. `augment` libraries are not baked
/// (they are rebuilt into the cached sysroot by `--build` at consume time).
class ToolchainImage {
  const ToolchainImage._();

  /// Workspace root baked into the image (the consumer passes `-w` this).
  static const workspace = '/emb';

  /// Default base image: small, and ships a cmake new enough for the embedder.
  static const defaultFrom = 'debian:bookworm-slim';

  /// The platform-dir path inside the image for [triple] + [sysrootKey].
  static String _platformDir(String triple, String sysrootKey) =>
      '$workspace/.config/flutter_workspace/cross-$triple-$sysrootKey';

  /// The Dockerfile that bakes the toolchain + sysroot into an image.
  static String dockerfile({
    required String triple,
    required String sysrootKey,
    String? toolchainVersion,
    String fromImage = defaultFrom,
  }) {
    final dir = _platformDir(triple, sysrootKey);
    return '''
# syntax=docker/dockerfile:1
# Generated by `emb cross --dockerfile`: a prebuilt arm-gnu cross toolchain +
# sysroot so CI pulls instead of resolving. Build (context = this directory):
#   docker build -t <tag> .
# Use it (the sysroot_key must match the manifest):
#   container: <tag>
#   emb cross <manifest> --target <name> --build -w $workspace
FROM $fromImage
# Build tooling: cmake/ninja/meson/make/pkg-config + the embedder's host codegen
# (wayland-scanner via libwayland-bin; git/curl for the engine-header fetch).
# meson builds `augment` libraries (e.g. libdisplay-info) into the sysroot.
RUN apt-get update \\
 && apt-get install -y --no-install-recommends \\
      cmake ninja-build meson make pkg-config tar xz-utils rsync ca-certificates \\
      libwayland-bin git curl \\
 && rm -rf /var/lib/apt/lists/*
ENV FLUTTER_WORKSPACE=$workspace
COPY toolchain $dir/toolchain
COPY sysroot $dir/sysroot
LABEL org.opencontainers.image.title="emb cross toolchain: $triple" \\
      emb.provider="arm-gnu" \\
      emb.triple="$triple" \\
      emb.toolchain_version="${toolchainVersion ?? ''}" \\
      emb.sysroot_key="$sysrootKey"
''';
  }

  /// `.dockerignore` keeping the build context to just `toolchain/` + `sysroot/`
  /// (excludes `downloads/` images/tarballs, `debs/`, the apt cache, etc.).
  static String dockerignore() => '''
# Keep the image lean — only the toolchain + sysroot are needed.
*
!toolchain
!sysroot
''';
}
