/// Emits a Dockerfile (+ `.dockerignore`) that bakes a resolved **arm-gnu**
/// cross toolchain + sysroot into an OCI image, so CI pulls a ready toolchain
/// instead of re-downloading and extracting it every run.
///
/// The build context is the provider's platform dir
/// (`cross-<triple>-<sysrootKey>/`), so the only `COPY` sources are its
/// `toolchain/` and `sysroot/` subdirs. The image bakes them at a **fixed**
/// workspace (`/emb`) under the same `cross-<triple>-<sysrootKey>` path emb
/// computes, so a later `emb cross <manifest> --build -w /emb` resolves as a
/// cache hit (the providers skip download/extract when the dir is populated)
/// and only re-emits the toolchain file for the in-image paths.
///
/// The sysroot's symlinks are relativized at resolve time, so it relocates from
/// the build host's path to `/emb` cleanly. `augment` libraries are not baked
/// (they are rebuilt into the cached sysroot by `--build` at consume time).
class ToolchainImage {
  const ToolchainImage._();

  /// Workspace root baked into the image (the consumer passes `-w` this).
  static const workspace = '/emb';

  /// Default base image: small, and ships a cmake new enough for the embedder.
  static const defaultFrom = 'debian:bookworm-slim';

  /// The platform-dir path inside the image for [triple] + [sysrootKey].
  static String _platformDir(String triple, String sysrootKey) =>
      '$workspace/.config/flutter_workspace/cross-$triple-$sysrootKey';

  /// The Dockerfile that bakes the toolchain + sysroot into an image.
  static String dockerfile({
    required String triple,
    required String sysrootKey,
    String? toolchainVersion,
    String fromImage = defaultFrom,
  }) {
    final dir = _platformDir(triple, sysrootKey);
    return '''
# syntax=docker/dockerfile:1
# Generated by `emb cross --dockerfile`: a prebuilt arm-gnu cross toolchain +
# sysroot so CI pulls instead of resolving. Build (context = this directory):
#   docker build -t <tag> .
# Use it (the sysroot_key must match the manifest):
#   container: <tag>
#   emb cross <manifest> --target <name> --build -w $workspace
FROM $fromImage
# Build tooling: cmake/ninja/meson/pkg-config + the embedder's host codegen
# (wayland-scanner via libwayland-bin; git/curl for the engine-header fetch).
# build-essential gives meson a native (build-machine) compiler — required to
# configure even a cross build when rebuilding `augment` libs (libdisplay-info).
RUN apt-get update \\
 && apt-get install -y --no-install-recommends \\
      cmake ninja-build meson build-essential pkg-config \\
      tar xz-utils rsync ca-certificates libwayland-bin git curl \\
 && rm -rf /var/lib/apt/lists/*
ENV FLUTTER_WORKSPACE=$workspace
COPY toolchain $dir/toolchain
COPY sysroot $dir/sysroot
LABEL org.opencontainers.image.title="emb cross toolchain: $triple" \\
      emb.provider="arm-gnu" \\
      emb.triple="$triple" \\
      emb.toolchain_version="${toolchainVersion ?? ''}" \\
      emb.sysroot_key="$sysrootKey"
''';
  }

  /// Device-rootfs subtrees pruned from the baked sysroot. These are never used
  /// when cross-compiling on the build host, so dropping them slims the image
  /// without affecting builds: runtime data/docs, bundled apps, kernel/firmware,
  /// and target executables. Headers, libraries (`usr/lib/<triple>`),
  /// pkgconfig/cmake metadata, and the wayland protocol XMLs are all kept.
  static const sysrootPrune = <String>[
    'boot',
    'var',
    'usr/src', // kernel/build sources (linux-libc-dev headers live in include/)
    'usr/games',
    'usr/bin', // target executables — cross builds invoke host tools only
    'usr/sbin',
    'usr/lib/firmware',
    'usr/lib/modules',
    'usr/lib/chromium',
    'usr/lib/firefox-esr',
    'usr/lib/u-boot',
    'usr/lib/linux-image-*',
    'usr/share/locale',
    'usr/share/doc',
    'usr/share/man',
    'usr/share/info',
    'usr/share/fonts',
    'usr/share/icons',
    'usr/share/themes',
    'usr/share/sounds',
    'usr/share/help',
    'usr/share/wallpapers',
    'usr/share/backgrounds',
  ];

  /// `.dockerignore` keeping the build context to just `toolchain/` + a slimmed
  /// `sysroot/` (excludes `downloads/` images/tarballs, `debs/`, the apt cache,
  /// and the device-rootfs bloat listed in [sysrootPrune]).
  static String dockerignore() {
    final prune = sysrootPrune.map((p) => 'sysroot/$p').join('\n');
    return '''
# Keep the image lean — only the toolchain + a cross-build sysroot are needed.
*
!toolchain
!sysroot
# Slim the baked sysroot: drop device-rootfs data/apps/kernel/firmware and
# target executables; keep headers, libraries, pkgconfig/cmake, wayland XMLs.
$prune
''';
  }
}
