import 'dart:convert';

import 'package:crypto/crypto.dart';

/// Emits a Dockerfile (+ `.dockerignore`) that bakes a resolved **arm-gnu**
/// cross toolchain + sysroot into an OCI image, so CI pulls a ready toolchain
/// instead of re-downloading and extracting it every run.
///
/// The build context is the provider's platform dir
/// (`cross-<triple>-<sysrootKey>/`), so the only `COPY` sources are its
/// `toolchain/` and `sysroot/` subdirs. The image bakes them at a **fixed**
/// workspace (`/emb`) under the same `cross-<triple>-<sysrootKey>` path emb
/// computes, so a later `emb cross <manifest> --build -w /emb` resolves as a
/// cache hit (the providers skip download/extract when the dir is populated)
/// and only re-emits the toolchain file for the in-image paths.
///
/// The sysroot's symlinks are relativized at resolve time, so it relocates from
/// the build host's path to `/emb` cleanly. `augment` libraries are not baked
/// (they are rebuilt into the cached sysroot by `--build` at consume time).
class ToolchainImage {
  const ToolchainImage._();

  /// Workspace root baked into the image (the consumer passes `-w` this).
  static const workspace = '/emb';

  /// Default base image: small, and ships a cmake new enough for the embedder.
  static const defaultFrom = 'debian:bookworm-slim';

  /// The Dockerfile for a cross **build environment**: the host build tooling
  /// and codegen, with no cross toolchain or sysroot baked in. The consumer
  /// fetches those from the shared cache (or resolves them) at build time, so
  /// one image is target-agnostic and never ships a multi-GB — or, worse, a
  /// dangling — sysroot.
  ///
  /// [hostDevPackages] are extra build-machine `-dev` packages a target's
  /// `host_dev_packages` declares (e.g. `libpugixml-dev` for the host
  /// wayland-cxx-scanner) — installed alongside the fixed build tooling so a
  /// `host: true` augment can compile in the image.
  static String dockerfile({
    required String triple,
    required String sysrootKey,
    String? toolchainVersion,
    String fromImage = defaultFrom,
    List<String> hostDevPackages = const [],
  }) {
    final hostDev = hostDevPackages.isEmpty
        ? ''
        : '      ${hostDevPackages.join(' ')} \\\n';
    return '''
# syntax=docker/dockerfile:1
# Generated by `emb cross --dockerfile`: a cross build environment (host
# toolchain + codegen). The cross toolchain and sysroot are fetched from the
# shared cache / resolved at build time, not baked in. Build:
#   docker build -t <tag> .
# Use it:
#   container: <tag>
#   emb cross <manifest> --target <name> --build -w $workspace
FROM $fromImage
# Build tooling: cmake/ninja/meson/pkg-config + the embedder's host codegen
# (wayland-scanner via libwayland-bin; git/curl for the engine-header fetch).
# build-essential gives meson a native (build-machine) compiler — required to
# configure even a cross build when rebuilding `augment` libs (libdisplay-info,
# which also reads hwdata's /usr/share/hwdata/pnp.ids at build time).
RUN apt-get update \\
 && apt-get install -y --no-install-recommends \\
      cmake ninja-build meson build-essential pkg-config hwdata \\
      tar xz-utils rsync ca-certificates libwayland-bin git curl \\
$hostDev && rm -rf /var/lib/apt/lists/*
ENV FLUTTER_WORKSPACE=$workspace
LABEL org.opencontainers.image.title="emb cross build env: $triple" \\
      emb.provider="arm-gnu" \\
      emb.triple="$triple" \\
      emb.toolchain_version="${toolchainVersion ?? ''}" \\
      emb.sysroot_key="$sysrootKey"
''';
  }

  /// `.dockerignore` for the build context: nothing is copied (the toolchain
  /// and sysroot are fetched at build time, not baked), so keep the context
  /// empty — only the Dockerfile itself is used.
  static String dockerignore() => '*\n';

  /// Content-addressed image tag `<sysrootKey>-<toolset hash>`, where the
  /// toolset hash covers [dockerfileContent] + [dockerignoreContent]. A
  /// toolset/emitter change (new base image, apt list) yields a new tag even
  /// when [sysrootKey] is unchanged, so a publish re-builds instead of skipping
  /// and serving a stale image.
  static String tagFor(
    String sysrootKey,
    String dockerfileContent,
    String dockerignoreContent,
  ) {
    final hash = sha256
        .convert(utf8.encode('$dockerfileContent\n$dockerignoreContent'))
        .toString()
        .substring(0, 12);
    return '$sysrootKey-$hash';
  }

  /// [tagFor] computed from this image's own emitted Dockerfile + dockerignore.
  static String imageTag({
    required String triple,
    required String sysrootKey,
    String? toolchainVersion,
    String fromImage = defaultFrom,
    List<String> hostDevPackages = const [],
  }) => tagFor(
    sysrootKey,
    dockerfile(
      triple: triple,
      sysrootKey: sysrootKey,
      toolchainVersion: toolchainVersion,
      fromImage: fromImage,
      hostDevPackages: hostDevPackages,
    ),
    dockerignore(),
  );
}
