import 'dart:io';

import 'package:emb_cli/src/cross/cross_arch.dart';
import 'package:path/path.dart' as p;

/// Writes build-system toolchain files for providers that don't ship their own
/// (the ARM GNU and Yocto recipe-sysroot paths). A Yocto SDK already carries
/// `OEToolchainConfig.cmake` + a meson cross file, so its provider sets those
/// on the profile directly and never calls this.
///
/// All inputs are the bare pieces of a resolved environment rather than a full
/// `CrossProfile`, because providers emit *before* the profile's
/// `cmakeToolchainFile`/`mesonCrossFile` fields are populated.
class ToolchainEmitter {
  const ToolchainEmitter();

  /// Emit a CMake toolchain file into [outDir], returning its path. [fileName]
  /// overrides the default name so cpu-variant targets sharing one sysroot dir
  /// don't clobber each other's toolchain file.
  String emitCMake({
    required Directory outDir,
    required String triple,
    required String crossBin,
    required String sysroot,
    required List<String> cpuFlags,
    String? fileName,
  }) {
    outDir.createSync(recursive: true);
    final file = File(
      p.join(outDir.path, fileName ?? '$triple-toolchain.cmake'),
    );
    final cpu = cpuFlags.join(' ');
    file.writeAsStringSync('''
# Auto-generated by emb — CMake cross toolchain ($triple).
set(CMAKE_SYSTEM_NAME      Linux)
set(CMAKE_SYSTEM_PROCESSOR ${cpuFamilyOfTriple(triple)})

set(_xc_bin     "$crossBin")
set(_xc_sysroot "$sysroot")
set(_xc_cpu     "$cpu")

set(CMAKE_C_COMPILER   "\${_xc_bin}/$triple-gcc")
set(CMAKE_CXX_COMPILER "\${_xc_bin}/$triple-g++")
set(CMAKE_AR           "\${_xc_bin}/$triple-ar")
set(CMAKE_STRIP        "\${_xc_bin}/$triple-strip")
set(CMAKE_SYSROOT      "\${_xc_sysroot}")

set(CMAKE_C_FLAGS_INIT   "\${_xc_cpu}")
set(CMAKE_CXX_FLAGS_INIT "\${_xc_cpu}")

# Search programs on the host, but headers/libs/packages only in the sysroot.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
''');
    return file.path;
  }

  /// Emit a Meson cross file into [outDir], returning its path. Used by the
  /// recipe-sysroot path (and by the augmentation builder for meson packages).
  String emitMeson({
    required Directory outDir,
    required String triple,
    required String crossBin,
    required String sysroot,
    required List<String> cpuFlags,
    String? fileName,
  }) {
    outDir.createSync(recursive: true);
    final file = File(p.join(outDir.path, fileName ?? '$triple-meson.cross'));
    final argList = cpuFlags.map((f) => "'$f'").join(', ');
    // The link step needs the crt/library search flags (`-mcpu`, `-B`, `-L`)
    // too — meson keeps compile and link args separate, so without these an
    // executable target fails to find crt1.o / -lm. The `-I` include flags are
    // compile-only.
    final linkArgs = cpuFlags
        .where((f) => !f.startsWith('-I'))
        .map((f) => "'$f'")
        .join(', ');
    final cpuFamily = cpuFamilyOfTriple(triple);
    file.writeAsStringSync('''
# Auto-generated by emb — Meson cross file ($triple).
[binaries]
c = '$crossBin/$triple-gcc'
cpp = '$crossBin/$triple-g++'
ar = '$crossBin/$triple-ar'
strip = '$crossBin/$triple-strip'
pkg-config = 'pkg-config'
# Run target binaries built during the cross build (codegen tools used in
# custom_target/run_target, and `meson test`) under qemu-user. Without this
# meson aborts at setup ("exe wrapper ... needed") for any project that
# executes a freshly-built target executable — e.g. a code generator. `-L`
# points qemu at the sysroot so it finds the target ld-linux + shared libs.
exe_wrapper = ['qemu-$cpuFamily-static', '-L', '$sysroot']

[host_machine]
system = 'linux'
cpu_family = '$cpuFamily'
cpu = '$cpuFamily'
endian = 'little'

[built-in options]
c_args = ['--sysroot=$sysroot'${argList.isNotEmpty ? ', $argList' : ''}]
cpp_args = ['--sysroot=$sysroot'${argList.isNotEmpty ? ', $argList' : ''}]
c_link_args = ['--sysroot=$sysroot'${linkArgs.isNotEmpty ? ', $linkArgs' : ''}]
cpp_link_args = ['--sysroot=$sysroot'${linkArgs.isNotEmpty ? ', $linkArgs' : ''}]
''');
    return file.path;
  }
}
