import 'dart:io';

import 'package:emb_cli/src/cross/cross_arch.dart';
import 'package:emb_cli/src/cross/determinism.dart';
import 'package:path/path.dart' as p;

/// Writes build-system toolchain files for providers that don't ship their own
/// (the ARM GNU and Yocto recipe-sysroot paths). A Yocto SDK already carries
/// `OEToolchainConfig.cmake` + a meson cross file, so its provider sets those
/// on the profile directly and never calls this.
///
/// All inputs are the bare pieces of a resolved environment rather than a full
/// `CrossProfile`, because providers emit *before* the profile's
/// `cmakeToolchainFile`/`mesonCrossFile` fields are populated.
class ToolchainEmitter {
  const ToolchainEmitter();

  /// Emit a CMake toolchain file into [outDir], returning its path. [fileName]
  /// overrides the default name so cpu-variant targets sharing one sysroot dir
  /// don't clobber each other's toolchain file.
  String emitCMake({
    required Directory outDir,
    required String triple,
    required String crossBin,
    required String sysroot,
    required List<String> cpuFlags,
    String? fileName,
  }) {
    outDir.createSync(recursive: true);
    final file = File(
      p.join(outDir.path, fileName ?? '$triple-toolchain.cmake'),
    );
    final cpu = [
      ...cpuFlags,
      ...prefixMapFlags(
        toolchainPrefixMap(sysroot: sysroot, crossBin: crossBin),
      ),
    ].join(' ');
    file.writeAsStringSync('''
# Auto-generated by emb — CMake cross toolchain ($triple).
set(CMAKE_SYSTEM_NAME      Linux)
set(CMAKE_SYSTEM_PROCESSOR ${cpuFamilyOfTriple(triple)})

set(_xc_bin     "$crossBin")
set(_xc_sysroot "$sysroot")
set(_xc_cpu     "$cpu")

set(CMAKE_C_COMPILER   "\${_xc_bin}/$triple-gcc")
set(CMAKE_CXX_COMPILER "\${_xc_bin}/$triple-g++")
set(CMAKE_AR           "\${_xc_bin}/$triple-ar")
set(CMAKE_STRIP        "\${_xc_bin}/$triple-strip")
set(CMAKE_SYSROOT      "\${_xc_sysroot}")

set(CMAKE_C_FLAGS_INIT   "\${_xc_cpu}")
set(CMAKE_CXX_FLAGS_INIT "\${_xc_cpu}")

# Search programs on the host, but headers/libs/packages only in the sysroot.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
''');
    return file.path;
  }

  /// Emit a Meson cross file into [outDir], returning its path. Used by the
  /// recipe-sysroot path (and by the augmentation builder for meson packages).
  String emitMeson({
    required Directory outDir,
    required String triple,
    required String crossBin,
    required String sysroot,
    required List<String> cpuFlags,
    String? fileName,
  }) {
    outDir.createSync(recursive: true);
    final file = File(p.join(outDir.path, fileName ?? '$triple-meson.cross'));
    // Prefix-map flags are compile-only (they neutralize recorded build paths),
    // so they join the compile args but not the link args below.
    final compileFlags = [
      ...cpuFlags,
      ...prefixMapFlags(
        toolchainPrefixMap(sysroot: sysroot, crossBin: crossBin),
      ),
    ];
    final argList = compileFlags.map((f) => "'$f'").join(', ');
    // The link step needs the crt/library search flags (`-mcpu`, `-B`, `-L`)
    // too — meson keeps compile and link args separate, so without these an
    // executable target fails to find crt1.o / -lm. The include flags
    // (`-I`, `-isystem`) are compile-only.
    final linkArgs = cpuFlags
        .where((f) => !f.startsWith('-I') && !f.startsWith('-isystem'))
        .map((f) => "'$f'")
        .join(', ');
    final cpuFamily = cpuFamilyOfTriple(triple);
    file.writeAsStringSync('''
# Auto-generated by emb — Meson cross file ($triple).
[binaries]
c = '$crossBin/$triple-gcc'
cpp = '$crossBin/$triple-g++'
ar = '$crossBin/$triple-ar'
strip = '$crossBin/$triple-strip'
pkg-config = 'pkg-config'
# No exe_wrapper: emb cross builds do not run freshly-built target binaries
# during the build — code generators are consumed as host tools (e.g. a host
# scanner resolved via CMake find_program), not cross-built and executed — so
# meson never needs an emulator to run a target binary on the build host.

[host_machine]
system = 'linux'
cpu_family = '$cpuFamily'
cpu = '$cpuFamily'
endian = 'little'

[built-in options]
c_args = ['--sysroot=$sysroot'${argList.isNotEmpty ? ', $argList' : ''}]
cpp_args = ['--sysroot=$sysroot'${argList.isNotEmpty ? ', $argList' : ''}]
c_link_args = ['--sysroot=$sysroot'${linkArgs.isNotEmpty ? ', $linkArgs' : ''}]
cpp_link_args = ['--sysroot=$sysroot'${linkArgs.isNotEmpty ? ', $linkArgs' : ''}]
''');
    return file.path;
  }
}
