import 'package:emb_cli/src/host/host_info.dart';
import 'package:emb_cli/src/workspace/workspace.dart';

/// Generate the contents of `setup_env.sh` for [workspace].
///
/// Ports the core, portable parts of the legacy `setup_env.sh`: it puts the
/// workspace Flutter SDK (and its bundled Dart) on `PATH`, and sets
/// `FLUTTER_WORKSPACE`, `PUB_CACHE`, `XDG_CONFIG_HOME`, `HOST_ARCH_GOOGLE`, and
/// (when known) `FLUTTER_ENGINE_VERSION`. Machine-specific toolchain/LLVM paths
/// and a hardcoded engine commit are intentionally omitted — emb resolves the
/// engine/gen_snapshot itself, and per-component env comes from manifests.
String generateSetupEnv({
  required Workspace workspace,
  required HostInfo host,
  String? engineVersion,
}) {
  final root = workspace.root.path;
  const flutterBin = r'$FLUTTER_WORKSPACE/flutter/bin';
  const dartBin = r'$FLUTTER_WORKSPACE/flutter/bin/cache/dart-sdk/bin';
  final lines = <String>[
    '#!/bin/sh',
    '# Generated by `emb env`. Re-run after moving the workspace.',
    '',
    'export FLUTTER_WORKSPACE="$root"',
    'export PATH="$flutterBin:$dartBin:\$PATH"',
    r'export PUB_CACHE="$FLUTTER_WORKSPACE/.config/flutter_workspace/pub_cache"',
    r'export XDG_CONFIG_HOME="$FLUTTER_WORKSPACE/.config/flutter"',
    'export HOST_ARCH_GOOGLE="${host.flutterArch}"',
    if (engineVersion != null && engineVersion.isNotEmpty)
      'export FLUTTER_ENGINE_VERSION="$engineVersion"',
    '',
    r'echo "FLUTTER_WORKSPACE=$FLUTTER_WORKSPACE"',
    '',
  ];
  return '${lines.join('\n')}\n';
}
